title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- .github
- scripts
- vendor
- logs
- assets
- .github
- data
ext:
- go
- js
- tmpl
- ini
enablerun: false
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - gofmt -w ./
  - go mod tidy
  - go mod vendor
  - ps -ef|grep 'imail service'| grep -v grep | awk '{print $2}' | xargs kill -9
  - make build
  - make run
  after:
  - ps -ef|grep 'imail service'| grep -v grep | awk '{print $2}' | xargs kill -9 
  exit:
  - ps -ef|grep 'imail service'| grep -v grep
  - ps -ef|grep 'imail service'| grep -v grep | awk '{print $2}' | xargs kill -9
  - rm -rf ./imail